title: 'Infocomm Media Development Authority'
title-abbreviated: IMDA
description: Code@SG
url: 'https://codesg.imda.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
kramdown:
  parse_block_html: true
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
resources_name: events
copyright_agency: 'IMDA. All rights reserved'
future: true
favicon: /images/SGD-logo.png
google_analytics: UA-103556192-2
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
staging: https://isomer-dlp-staging.netlify.com/,
prod: https://isomer-dlp-prod.netlify.com/,
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
colors:
  primary-color: '#961C56'
  secondary-color: '#6F358D'
  # tertiary: '#7FA344'
  # ahmalikespie: '#262420'
  media-colors:
    - title: media-color-one
      color: '#49759a'
    - title: media-color-two
      color: '#00838f'
    - title: media-color-three
      color: '#006666'
    - title: media-color-four
      color: '#46A3A3'
    - title: media-color-five
      color: '#006666'
